### ISSUE TITLE
Textures not Loading

### ISSUE THREAD

**Issue by m-inecraft** [lumien231/Custom-Main-Menu#105]
My Textures are not loading ...
I am using the ResourceLoader-MC1.7.10-1.3
and the CustomMainMenu-MC1.7.10-1.9.2

My Config File:
http://pastebin.com/E3NEu1hm

The result: 
http://puu.sh/oeoVZ/47cba6cf8c.jpg

please help to fix

**Comment by lumien231** [comment]
Make the Resource Domain lowercase & remove the / before textures. If it still doesn't work Post your Folder structure please

**Comment by m-inecraft** [comment]
dosen't work -.- \mineworld-reloaded\resources\Modpack\Textures\Mineworld-Reloaded.png
Client Log: 
http://pastebin.com/Fe68DdVG

**Comment by lumien231** [comment]
You didn't remove the / before Textures -.- . The Modpack folder also has to be lowercase

**Comment by m-inecraft** [comment]
I have coorected that 
same than before
http://pastebin.com/k0csTfnk

**Comment by lumien231** [comment]
Could you post image of folder structure + json + log for that case again please?

**Comment by legracen** [comment]
\Minecraft\Instances\Chaos Portal Pack\resources\cpp\textures\gui
`{
    "images":
    {
        "title":
        {
            "image" : "cpp:textures/gui/banner.png",
            "posX" : -260,
            "posY" : 20,
            "width" : 512,
            "height" : 512,
            "alignment" : "top_center"
        }
    },
    
    "buttons":
    {
        "singleplayer":
        {
            "text" : "menu.singleplayer",
            "posX" : -100,
            "posY" : 48,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },
        
        "multiplayer":
        {
            "text" : "menu.multiplayer",
            "posX" : -100,
            "posY" : 72,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
        
        "mods":
        {
            "text" : "Mods",
            "posX" : -100,
            "posY" : 96,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },
            
        "options":
        {
            "text" : "menu.options",
            "posX" : -100,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },
        
        "quit":
        {
            "text" : "menu.quit",
            "posX" : 2,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "quit"
            }
        },
        
        "language":
        {
            "text" : "",
            "posX" : -124,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
        
        "refresh":
        {
            "text" : "",
            "posX" : -154,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "texture" : "custommainmenu:textures/gui/buttons.png",
            "action" : 
            {
                "type" : "refresh"
            }
        }
    },
    
    "texts":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right"
        },
        
        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -50,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },
    
    "other":
    {
        "splash-text":
        {
            "posX" : 90,
            "posY" : 70,
            "color" : -256,
            "alignment" : "top_center",
            "texts" : "file:minecraft:texts/splashes.txt"
        },
        
        "panorama":
        {
            "images" : "minecraft:textures/gui/title/background/panorama_%c.png",
            "animate" : true,
            "animationSpeed" : 1,
            "blur" : true,
            "gradient" : true
        }
    }
}`
`[07:50:23] [Client thread/WARN]: Failed to load texture: cpp:textures/gui/banner.png
java.io.FileNotFoundException: cpp:textures/gui/banner.png
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:71) ~[brg.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:29) ~[bpu.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:89) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:45) [bqf.class:?]
	at lumien.custommainmenu.lib.textures.TextureResourceLocation.bind(TextureResourceLocation.java:16) [TextureResourceLocation.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:368) [GuiCustom.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) [blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
`

**Comment by legracen** [comment]
I am having the same issue:

Folder structure:
\Minecraft\Instances\Chaos Portal Pack\resources\cpp\textures\gui

json:
[http://pastebin.com/D24Huyk6](url)

log:
[http://pastebin.com/G7h75v32](url)
