### ISSUE TITLE
Game folder

### ISSUE THREAD

**Issue by GuillaumeSX** [lumien231/Custom-Main-Menu#116]
In your code, please use `Minecraft.getMinecraft().mcDataDir` instead of `new File(".")`.

It's better for launchers that use a subfolder in the .minecraft

Thanks ;)

**Comment by lumien231** [comment]
And your issue did not get fixed by using Resource Loader version 1.3?

**Comment by GuillaumeSX** [comment]
I get the impression that not :/

**Comment by GuillaumeSX** [comment]
I think the probel comes from Resources Loader :/

**Comment by lumien231** [comment]
Yes it does but i thought i fixed this in 1.3, could you post your log & folder structure please?

**Comment by GuillaumeSX** [comment]
Yes I do that this afternoon ;)

2016-05-29 22:26 GMT+02:00 Lumien <notifications@github.com>:

**Comment by GuillaumeSX** [comment]
`[17:27:10] [Client thread/WARN]: Failed to load texture: minecraft:mainmenu	exturesg.png
java.io.FileNotFoundException: minecraft:mainmenu	exturesg.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:67) ~[brg.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:29) ~[bpu.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:94) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:50) [bqf.class:?]
	at lumien.custommainmenu.lib.textures.TextureResourceLocation.bind(TextureResourceLocation.java:16) [TextureResourceLocation.class:?]
	at lumien.custommainmenu.gui.GuiCustom.drawPanorama(GuiCustom.java:569) [GuiCustom.class:?]
	at lumien.custommainmenu.gui.GuiCustom.renderSkybox(GuiCustom.java:480) [GuiCustom.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:303) [GuiCustom.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1397) [blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at fr.minecraftforgefrance.updater.Updater.runMinecraft(Updater.java:130) [updater-2.1.0.jar:?]
	at fr.minecraftforgefrance.updater.Updater.<init>(Updater.java:97) [updater-2.1.0.jar:?]
	at fr.minecraftforgefrance.updater.Updater.main(Updater.java:36) [updater-2.1.0.jar:?]
`


The structure is : `%appdata%\Roaming\.minecraft\modpacks\Craft Your Glory\config\CustomMainMenu\resources\mainmenu\bg.png`

It's enough?

**Comment by lumien231** [comment]
The resources folder is in the main minecraft folder, not the CustomMainMenu config folder.

**Comment by GuillaumeSX** [comment]
Yes ! but my modpacks repertories is a subfolder of the .minecraft, look that : https://i.imgur.com/3NP5onm.png

**Comment by GuillaumeSX** [comment]
And i've the same problem, when i paste this config (an ressources) in the modpacks configs subfolder : 
https://i.imgur.com/CoLlTDL.png == https://i.imgur.com/HjPgKpB.png

**Comment by lumien231** [comment]
Yes the resources folder is meant to be in the folder on the first screenshot.

**Comment by GuillaumeSX** [comment]
\---Craft Your Glory
    |   Craft Your Glory.json
    |   options.txt
    |   optionsof.txt
    |   optionsshaders.txt
    |   usernamecache.json
    |   
    +---config
    |   |   forge.cfg
    |   |   forgeChunkLoading.cfg
    |   |   splash.properties
    |   |   
    |   \---CustomMainMenu
    |       |   mainmenu.json
    |       |   
    |       \---resources
    |           \---mainmenu
    |               \---textures
    |                   |   bg.png
    |                   |   
    |                   \---buttons
    |                           bg_hex2.png
    |                           lang.png
    |                           mods.png
    |                           multi.png
    |                           quit.png
    |                           settings.png
    |                           single.png
    |                           
    +---mods
    |       CustomMainMenu-MC1.7.10-1.3.jar
    |       modfake.jar
    |       OptiFine_1.7.10_HD_U_D4.jar
    |       ResourceLoader-MC1.7.10-1.3.jar
    |       ShadersModCore-v2.3.31-mc1.7.10-f.jar
    |       
    +---resourcepacks
    |       ChromaHills-64x1.7_1.0.9.zip
    |       SWFOpenerSetup-1.3.exe
    |       
    +---resources
    +---saves
    |   \---New World
    |       |   forcedchunks.dat
    |       |   level.dat
    |       |   level.dat_mcr
    |       |   level.dat_old
    |       |   session.lock
    |       |   
    |       +---data
    |       |       Mineshaft.dat
    |       |       Stronghold.dat
    |       |       Temple.dat
    |       |       Village.dat
    |       |       villages.dat
    |       |       
    |       +---DIM-1
    |       |   |   forcedchunks.dat
    |       |   |   
    |       |   \---data
    |       +---DIM1
    |       |   |   forcedchunks.dat
    |       |   |   
    |       |   \---data
    |       +---playerdata
    |       |       f2ec689c-56fd-3f99-a631-d3855814dec6.dat
    |       |       
    |       +---region
    |       |       r.-1.0.mca
    |       |       r.-1.1.mca
    |       |       r.0.-1.mca
    |       |       r.0.0.mca
    |       |       r.0.1.mca
    |       |       r.1.0.mca
    |       |       r.1.1.mca
    |       |       
    |       \---stats
    |               f2ec689c-56fd-3f99-a631-d3855814dec6.json
    |               
    \---shaderpacks
            SEUS v10.0 Lite.zip
            
Yo can see my modpacks subfolder, it is in !

**Comment by GuillaumeSX** [comment]
The json is the default JSON that i get on Curse website : 
`{
    "images":
    {
		"black_sp":
        {
            "image" : "mainmenu:textures/buttons/bg_hex2.png",
            "posX" : 44,
            "posY" : 18,
            "width" : 56,
            "height" : 68,
            "alignment" : "top_left"
        },
		"black_mp":
        {
            "image" : "mainmenu:textures/buttons/bg_hex2.png",
            "posX" : 102,
            "posY" : 18,
            "width" : 56,
            "height" : 68,
            "alignment" : "top_left"
        },
		"black_mod":
        {
            "image" : "mainmenu:textures/buttons/bg_hex2.png",
            "posX" : 73,
            "posY" : 71,
            "width" : 56,
            "height" : 68,
            "alignment" : "top_left"
        },
		"black_sett":
        {
            "image" : "mainmenu:textures/buttons/bg_hex2.png",
            "posX" : 15,
            "posY" : 71,
            "width" : 56,
            "height" : 68,
            "alignment" : "top_left"
        }
	
	},
    
    "buttons":
    {     
	
		"sp_button":
        {
            "text" : "",
			"normalTextColor" : 12303291,
			"hoverTextColor" : 3125670,
			"texture" : "mainmenu:textures/buttons/single.png",
            "posX" : 40,
            "posY" : 20,
            "width" : 64,
            "height" : 64,
			"imageWidth" : 128,
			"imageHeight" : 128,
			"alignment" : "left_top",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },
		"multiplayer":
        {
            "text" : "",
			"normalTextColor" : 12303291,
			"hoverTextColor" : 3125670,
			"texture" : "mainmenu:textures/buttons/multi.png",
            "posX" : 98,
            "posY" : 20,
            "width" : 64,
            "height" : 64,
			"imageWidth" : 128,
			"imageHeight" : 128,
			"alignment" : "left_top",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
               
		"options":
        {
            "text" : "",
			"normalTextColor" : 12303291,
			"hoverTextColor" : 3125670,
			"texture" : "mainmenu:textures/buttons/settings.png",
            "posX" : 11,
            "posY" : 73,
            "width" : 64,
            "height" : 64,
			"imageWidth" : 128,
			"imageHeight" : 128,
			"alignment" : "left_top",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },

                    

        "mods":
        {
            "text" : "",
			"normalTextColor" : 12303291,
			"hoverTextColor" : 3125670,
			"texture" : "mainmenu:textures/buttons/mods.png",
            "posX" : 69,
            "posY" : 73,
            "width" : 64,
            "height" : 64,
			"imageWidth" : 128,
			"imageHeight" : 128,
			"alignment" : "left_top",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },	        
		"quit":
        {
            "text" : "",
			"normalTextColor" : 12303291,
			"hoverTextColor" : 3125670,
			"texture" : "mainmenu:textures/buttons/quit.png",
            "posX" : -69,
            "posY" : -85,
            "width" : 64,
            "height" : 64,
			"imageWidth" : 128,
			"imageHeight" : 128,
			"alignment" : "bottom_right",
            "action" : 
            {
                "type" : "quit"
            }
        },        
		"language":
        {
            "text" : "",
			"normalTextColor" : 12303291,
			"hoverTextColor" : 3125670,
			"texture" : "mainmenu:textures/buttons/lang.png",
            "posX" : -127,
            "posY" : -85,
            "width" : 64,
            "height" : 64,
			"imageWidth" : 128,
			"imageHeight" : 128,
			"alignment" : "bottom_right",
            "action" : 
            {
                "type" : "quit"
            }
        },
        "versionChecker":
        {
            "text" : "Version-Checker",
            "posX" : 2,
            "posY" : -35,
            "width" : 100,
            "height" : 20,
			"imageWidth" : 100,
			"imageHeight" : 50,			
			"alignment" : "bottom_left",
            "wrappedButton" : 404
        }
	},
    
    "texts":
    {
        "mojang":
        {
            "text" : "Forge #forgeversion# for MC #mcversion# - Copyright Mojang AB. Do not distribute!",
            "posX" : 2,
            "posY" : -10,
            "color" : -1,
			"fontSize" : 1,
            "alignment" : "bottom_left"
        },
        
		"packTxt":
        {
            "text" : "AAIII - 0.0.1a",
            "posX" : 2,
            "posY" : 2,
            "color" : -1,
            "alignment" : "top_left"
        }
    },
    
    "other":
    {
		"background":
		{
			"image" : "mainmenu:textures/bg.png",
			"mode" : "stretch"
		}
    }
}`

**Comment by GuillaumeSX** [comment]
This is an exemple of a ressource loading error : 
`[09:23:16] [Client thread/WARN]: Failed to load texture: mainmenu:textures/buttons/lang.png
java.io.FileNotFoundException: mainmenu:textures/buttons/lang.png
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:71) ~[brg.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:29) ~[bpu.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:94) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:50) [bqf.class:?]
	at lumien.custommainmenu.lib.textures.TextureResourceLocation.bind(TextureResourceLocation.java:16) [TextureResourceLocation.class:?]
	at lumien.custommainmenu.gui.GuiCustomButton.func_146112_a(GuiCustomButton.java:76) [GuiCustomButton.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:411) [GuiCustom.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1397) [blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at fr.minecraftforgefrance.updater.Updater.runMinecraft(Updater.java:130) [updater-2.1.0.jar:?]
	at fr.minecraftforgefrance.updater.Updater.<init>(Updater.java:97) [updater-2.1.0.jar:?]
	at fr.minecraftforgefrance.updater.Updater.main(Updater.java:36) [updater-2.1.0.jar:?]`

**Comment by lumien231** [comment]
Again, the resources folder is not supposed to be in the CustomMainMenu config folder, it should be where your config folder is.

**Comment by IPv777** [comment]
Okay, i'm a noob, sorry, it works !
Thanks !

**Comment by ToggleLegit** [comment]
Hi, I know its a bit late but I have still an issue. When I am downloading the mod+ResourceLoader there is only a folder in .minecraft/config/CustomMainMenu/mainmenu
Nothing more, no resources or other things. I even made my own resources folder with everything in it but it wasn't working at all. 
I really need help and hope you still read this!
