### ISSUE TITLE
Crash-reports

### ISSUE THREAD

**Issue by Mchot** [lumien231/Custom-Main-Menu#14]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 15-1-22 P.M.1:59
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at lumien.custommainmenu.gui.GuiCustomMainMenu.func_73866_w_(GuiCustomMainMenu.java:103)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:797)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:551)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at lumien.custommainmenu.gui.GuiCustomMainMenu.func_73866_w_(GuiCustomMainMenu.java:103)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:797)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:551)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode, sharing), Oracle Corporation
	Memory: 16807480 bytes (16 MB) / 163610624 bytes (156 MB) up to 735903744 bytes (701 MB)
	JVM Flags: 1 total; -Xmx726m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1277 Minecraft Forge 10.13.2.1277 4 mods loaded, 4 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1277} [Forge Mod Loader] (forge-1.7.10-10.13.2.1277.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1277} [Minecraft Forge] (forge-1.7.10-10.13.2.1277.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CustomMainMenu{1.1} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Launched Version: 1.7.10-Forge10.13.2.1277
	LWJGL: 2.9.1
	OpenGL: GeForce 9300M GS/PCI/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
How to solve it?

**Comment by lumien231** [comment]
When does this happen?
