### ISSUE TITLE
Custom Logo not working

### ISSUE THREAD

**Issue by ma1201** [lumien231/Custom-Main-Menu#169]
[23:47:56] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:47:56] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:47:56] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[23:47:56] [main/INFO]: Forge Mod Loader version 12.18.3.2221 for Minecraft 1.10.2 loading
[23:47:56] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[23:47:56] [main/WARN]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:47:56] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:47:56] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[23:47:56] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:47:56] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:47:56] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:47:58] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[23:47:58] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[23:47:58] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:47:58] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[23:47:59] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:47:59] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[23:47:59] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[23:47:59] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[23:48:00] [Client thread/INFO]: Setting user: marius222222
[23:48:04] [Client thread/WARN]: Skipping bad option: lastServer:
[23:48:04] [Client thread/INFO]: LWJGL Version: 2.9.4
[23:48:05] [Client thread/INFO]: [net.minecraftforge.fml.client.SplashProgress:start:219]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 23.02.17 23:48
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 141987712 bytes (135 MB) / 275369984 bytes (262 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.54' Renderer: 'GeForce GTX 750/PCIe/SSE2'
[23:48:05] [Client thread/INFO]: MinecraftForge v12.18.3.2221 Initialized
[23:48:05] [Client thread/INFO]: Replaced 231 ore recipes
[23:48:06] [Client thread/INFO]: Found 0 mods from the command line. Injecting into mod discoverer
[23:48:06] [Client thread/INFO]: Searching C:\Users\ma1sc\AppData\Roaming\CustomModpack\mods for mods
[23:48:07] [Client thread/INFO]: Mod mercurius_updater is missing the required element 'name'. Substituting mercurius_updater
[23:48:07] [Client thread/WARN]: ****************************************
[23:48:07] [Client thread/WARN]: * The modid CustomMainMenu is not the same as it's lowercase version. Lowercasing will be enforced in 1.11
[23:48:07] [Client thread/WARN]: *  at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:143)
[23:48:07] [Client thread/WARN]: *  at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:128)
[23:48:07] [Client thread/WARN]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:48:07] [Client thread/WARN]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[23:48:07] [Client thread/WARN]: *  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:48:07] [Client thread/WARN]: *  at java.lang.reflect.Constructor.newInstance(Constructor.java:408)...
[23:48:07] [Client thread/WARN]: ****************************************
[23:48:07] [Client thread/WARN]: ****************************************
[23:48:07] [Client thread/WARN]: * The modid ResourceLoader is not the same as it's lowercase version. Lowercasing will be enforced in 1.11
[23:48:07] [Client thread/WARN]: *  at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:143)
[23:48:07] [Client thread/WARN]: *  at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:128)
[23:48:07] [Client thread/WARN]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:48:07] [Client thread/WARN]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[23:48:07] [Client thread/WARN]: *  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:48:07] [Client thread/WARN]: *  at java.lang.reflect.Constructor.newInstance(Constructor.java:408)...
[23:48:07] [Client thread/WARN]: ****************************************
[23:48:07] [Client thread/INFO]: Forge Mod Loader has identified 6 mods to load
[23:48:08] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge, mercurius_updater, CustomMainMenu, ResourceLoader] at CLIENT
[23:48:08] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge, mercurius_updater, CustomMainMenu, ResourceLoader] at SERVER
[23:48:08] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:mercurius_updater, FMLFileResourcePack:Custom Main Menu, FMLFileResourcePack:Resource Loader, CustomResources, CustomOverridingResources
[23:48:08] [Client thread/INFO]: Processing ObjectHolder annotations
[23:48:08] [Client thread/INFO]: Found 423 ObjectHolder annotations
[23:48:08] [Client thread/INFO]: Identifying ItemStackHolder annotations
[23:48:08] [Client thread/INFO]: Found 0 ItemStackHolder annotations
[23:48:08] [Client thread/INFO]: Applying holder lookups
[23:48:08] [Client thread/INFO]: Holder lookups applied
[23:48:08] [Client thread/INFO]: Applying holder lookups
[23:48:08] [Client thread/INFO]: Holder lookups applied
[23:48:08] [Client thread/INFO]: Applying holder lookups
[23:48:08] [Client thread/INFO]: Holder lookups applied
[23:48:08] [Client thread/INFO]: Configured a dormant chunk cache size of 0
[23:48:08] [Client thread/INFO]: Version Number exists, Using it: 1.9.4-1.0.1.16
[23:48:08] [Client thread/INFO]: File exists, Checking hash: C:\Users\ma1sc\AppData\Roaming\.minecraft\libraries\net\minecraftforge\Mercurius\1.9.4-1.0.1.16\Mercurius-1.9.4-1.0.1.16.jar
[23:48:08] [Client thread/INFO]:   Hash matches, Skipping download: 11eec5c5153885e4359946e402321af789aef969
[23:48:08] [Client thread/INFO]: Mercurius Jar contains all signed files! Continueing loading!
[23:48:08] [Forge Version Check/INFO]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[23:48:08] [Client thread/INFO]: Applying holder lookups
[23:48:08] [Client thread/INFO]: Holder lookups applied
[23:48:08] [Client thread/INFO]: Injecting itemstacks
[23:48:08] [Client thread/INFO]: Itemstack injection complete
[23:48:09] [Forge Version Check/INFO]: [Forge] Found status: OUTDATED Target: 12.18.3.2234
[23:48:09] [Sound Library Loader/INFO]: Starting up SoundSystem...
[23:48:10] [Thread-9/INFO]: Initializing LWJGL OpenAL
[23:48:10] [Thread-9/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[23:48:10] [Thread-9/INFO]: OpenAL initialized.
[23:48:10] [Sound Library Loader/INFO]: Sound engine started
[23:48:12] [Client thread/INFO]: Max texture size: 16384
[23:48:12] [Client thread/INFO]: Created: 16x16 textures-atlas
[23:48:13] [Client thread/INFO]: Injecting itemstacks
[23:48:13] [Client thread/INFO]: Itemstack injection complete
[23:48:13] [Client thread/INFO]: Forge Mod Loader has successfully loaded 6 mods
[23:48:13] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:mercurius_updater, FMLFileResourcePack:Custom Main Menu, FMLFileResourcePack:Resource Loader, CustomResources, CustomOverridingResources
[23:48:14] [Client thread/INFO]: SoundSystem shutting down...
[23:48:14] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[23:48:14] [Sound Library Loader/INFO]: Starting up SoundSystem...
[23:48:14] [Thread-12/INFO]: Initializing LWJGL OpenAL
[23:48:14] [Thread-12/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[23:48:14] [Thread-12/INFO]: OpenAL initialized.
[23:48:15] [Sound Library Loader/INFO]: Sound engine started
[23:48:15] [Client thread/INFO]: Max texture size: 16384
[23:48:16] [Client thread/INFO]: Created: 512x512 textures-atlas
[23:48:18] [Client thread/WARN]: Skipping bad option: lastServer:
[23:48:19] [Client thread/WARN]: Failed to load texture: modpack:Future.png
java.io.FileNotFoundException: modpack:Future.png
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:69) ~[bxi.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[bwa.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67) [bwf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:42) [bwf.class:?]
	at lumien.custommainmenu.lib.textures.TextureResourceLocation.bind(TextureResourceLocation.java:16) [TextureResourceLocation.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:357) [GuiCustom.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) [bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[23:52:38] [Client thread/INFO]: Stopping!
[23:52:38] [Client thread/INFO]: SoundSystem shutting down...
[23:52:38] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com

**Comment by ma1201** [comment]
CODE
{
    "images":
    {
        "title":
        {
            "image" : "modpack:Future.png",
            "posX" : -137,
            "posY" : 30,
            "width" : 512,
            "height" : 512,
            "imageWidth" : 234,
            "imageHeight" : 169,
            "alignment" : "top_center"
        }
    },

    "buttons":
    {
        "singleplayer":
        {
            "text" : "menu.singleplayer",
            "posX" : -100,
            "posY" : 48,
            "width" : 200,
            "height" : 20,
            "action" :
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },

        "multiplayer":
        {
            "text" : "menu.multiplayer",
            "posX" : -100,
            "posY" : 72,
            "width" : 200,
            "height" : 20,
            "action" :
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },

        "mods":
        {
            "text" : "fml.menu.mods",
            "posX" : -100,
            "posY" : 96,
            "width" : 200,
            "height" : 20,
            "action" :
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },

        "options":
        {
            "text" : "menu.options",
            "posX" : -100,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" :
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },

        "quit":
        {
            "text" : "menu.quit",
            "posX" : 2,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" :
            {
                "type" : "quit"
            }
        },

        "language":
        {
            "text" : "",
            "posX" : -124,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "action" :
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },

        "refresh":
        {
            "text" : "",
            "posX" : -154,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "texture" : "custommainmenu:textures/gui/buttons.png",
            "action" :
            {
                "type" : "refresh"
            }
        }
    },

    "labels":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right"
        },

        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -40,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },

    "other":
    {
        "splash-text":
        {
            "posX" : 90,
            "posY" : 70,
            "color" : -256,
            "alignment" : "top_center",
            "texts" : "file:minecraft:texts/splashes.txt"
        },

        "panorama":
        {
            "images" : "minecraft:textures/gui/title/background/panorama_%c.png",
            "animate" : true,
            "animationSpeed" : 1,
            "blur" : true,
            "gradient" : true
        }
    }
}

**Comment by ma1201** [comment]
Only Read under A detailed walkthrough of the error, its code path and all known details is as follows:
