### ISSUE TITLE
Read Resource Loader Page, but my textures are still showing as missing (purple/black squares)

### ISSUE THREAD

**Issue by canadiannickel** [lumien231/Custom-Main-Menu#184]
[21:26:12] [Client thread/WARN]: Failed to load texture: textures:background
java.io.FileNotFoundException: textures:background
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:67) ~[brg.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:29) ~[bpu.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:89) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:45) [bqf.class:?]
	at lumien.custommainmenu.lib.textures.TextureResourceLocation.bind(TextureResourceLocation.java:16) [TextureResourceLocation.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:312) [GuiCustom.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) [blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[21:26:12] [Client thread/WARN]: Failed to load texture: textures:title
java.io.FileNotFoundException: textures:title
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:67) ~[brg.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:29) ~[bpu.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:89) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:45) [bqf.class:?]
	at lumien.custommainmenu.lib.textures.TextureResourceLocation.bind(TextureResourceLocation.java:16) [TextureResourceLocation.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:368) [GuiCustom.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) [blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[21:26:13] [Client thread/INFO]: Loading blocks and textures...
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersBlock:0] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersBarrier:0] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersBed:0] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersButton:0] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersCollapsibleBlock:0] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersDaylightSensor:0] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersDoor:0] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersFlowerPot:0] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersGarageDoor:0] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersGate:0] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersHatch:0] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersLadder:0] (OpenToSky,SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersLever:0] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersPressurePlate:0] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersSafe:0] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersSlope:0] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersSlope:1] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersSlope:2] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersSlope:3] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersSlope:4] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Registered IModBlockHandler journeymap.client.model.mod.CarpentersBlocks$CommonHandler for: 'BlockMD [CarpentersBlocks:blockCarpentersStairs:0] (SpecialHandling)'.
[21:26:13] [Client thread/INFO]: Built BlockMD cache (7269) : BlockMD.reset count 1 avg 135.91ms
[21:26:13] [Client thread/INFO]: initBlocksTexture: 2048x2048 loaded in 197.852791ms
[21:26:13] [Client thread/INFO]: Existing color palette's resource packs and mod names match current loadout.
[21:26:13] [Client thread/INFO]: Loaded 6728 block colors from color palette file in 31ms: C:\Users\mason\AppData\Roaming\.minecraft\journeymap\colorpalette.json
[21:26:13] [Client thread/INFO]: Initialized 66 block colors from mods and resource packs in 32ms
[21:26:13] [Client thread/WARN]: Block with Error flag won't be saved to color palette: BlockMD [Thaumcraft:blockAiry:0] (Transparency,Error)
[21:26:13] [Client thread/WARN]: Block with Error flag won't be saved to color palette: BlockMD [AWWayofTime:spectralContainer:0] (Transparency,Error)

There is the full log

![resourcefolder](https://cloud.githubusercontent.com/assets/27321709/24937399/7c17465c-1efe-11e7-9188-1a1613a50cba.PNG)

My resource folder and textures folder (ignore the 2k17 symbol lol)

{
    "images":
    {
        "title":
        {
            "image" : "textures:title",
            "posX" : 0,
            "posY" : 0,
            "width" : 12,
            "height" : 12,
            "alignment" : "top_center"
        }
    },
    
    "buttons":
    {
        "singleplayer":
        {
            "text" : "By Yaself!",
            "posX" : -100,
            "posY" : 48,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },
        
        "multiplayer":
        {
            "text" : "With Ya Bois",
            "posX" : -100,
            "posY" : 72,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
        
        "mods":
        {
            "text" : "Mods",
            "posX" : -100,
            "posY" : 96,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },
            
        "options":
        {
            "text" : "menu.options",
            "posX" : -100,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },
        
        "quit":
        {
            "text" : "menu.quit",
            "posX" : 2,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "quit"
            }
        },
        
        "language":
        {
            "text" : "",
            "posX" : -124,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
        
        "refresh":
        {
            "text" : "",
            "posX" : -154,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "texture" : "custommainmenu:textures/gui/buttons.png",
            "action" : 
            {
                "type" : "refresh"
            }
        }
    },
    
    "texts":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right"
        },
        
        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -50,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },
    
    "other":
    {
        "splash-text":
        {
            "posX" : 90,
            "posY" : 70,
            "color" : -256,
            "alignment" : "top_center",
            "texts" : "file:minecraft:texts/splashes.txt"
        },
        
        "background":
        {
            "image" : "textures:background",
            "mode" : "fill"
        }
    }
}

The full custom main menu configuration file

![mccmmcrash](https://cloud.githubusercontent.com/assets/27321709/24937459/d25ea0fa-1efe-11e7-9792-7c5202b34608.PNG)

But, still forsaken by the missing texture image...

Can anyone help?

**Comment by lumien231** [comment]
You are missing the .png at the end of all your images.

**Comment by canadiannickel** [comment]
Thanks so much that worked. (Hate myself for being so stupid xD)
