### ISSUE TITLE
[SOLVED] Missing Texture only when I add Matter Overdrive

### ISSUE THREAD

**Issue by TimeLadyAboutTime** [lumien231/Custom-Main-Menu#199]
So, I'm making a modpack, first I installed only Custom Main Menu, Resource Loader and Ambience, configured my personalized main menu and everything worked just fine, but then when I added the rest of the mods, I get the missing texture(purple and black) bug

Prints(Sorry for being a camera picture and not a monitor screenshot)
Before the mods:
http://imgur.com/a/E5Vje

After The Mods:
http://imgur.com/a/FWgkO

CustomMainMenu Config (Absolutely nothing changed between working and not working)

```
{
    "images":
    {
         "title":
        {
            "image" : "skyforgemenu:textures/skyforgethunder.png",
            "posX" : -91,
            "posY" : -10,
            "width" : 170,
            "height" : 160,
            "alignment" : "center"
        },

         "black":
        {
            "image" : "skyforgemenu:textures/transparent.png",
            "posX" : -77,
            "posY" : -110,
            "width" : 140,
            "height" : 150,
            "alignment" : "center"
        }
    },
    
    "buttons":
    {
        "singleplayer":
        {
            "text" : "menu.singleplayer",
            "posX" : -75,
            "posY" : -30,
            "width" : 140,
            "height" : 10,
            "imageWidth":1000,
            "imageHeight":550,            
            "texture":"skyforgemenu:textures/blank.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },
        
        "multiplayer":
        {
            "text" : "menu.multiplayer",
            "posX" : -75,
            "posY" : -10,
            "width" : 140,
            "height" : 10,
            "imageWidth":800,
            "imageHeight":300,
            "texture":"skyforgemenu:textures/blank.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
        
        "mods":
        {
            "text" : "fml.menu.mods",
            "posX" : -75,
            "posY" : 10,
            "width" : 140,
            "height" : 10,
            "imageWidth":800,
            "imageHeight":300,
            "texture":"skyforgemenu:textures/blank.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },
            
        "options":
        {
            "text" : "menu.options",
            "posX" : -75,
            "posY" : 30,
            "width" : 140,
            "height" : 10,
            "imageWidth":800,
            "imageHeight":300,
            "texture":"skyforgemenu:textures/blank.png",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },
        
        "quit":
        {
            "text" : "menu.quit",
            "posX" : -75,
            "posY" : 50,
            "width" : 140,
            "height" : 10,
            "imageWidth":800,
            "imageHeight":300,
            "texture":"skyforgemenu:textures/blank.png",
            "action" : 
            {
                "type" : "quit"
            }
        },
        
        "language":
        {
            "text" : "",
            "posX" : -124,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
        
        "refresh":
        {
            "text" : "",
            "posX" : -154,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "texture" : "custommainmenu:textures/gui/buttons.png",
            "action" : 
            {
                "type" : "refresh"
            }
        }
    },
    
    "labels":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right"
        },
        
        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -40,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },
    
    "other":
    {
        "splash-text":
        {
            "posX" : 10,
            "posY" : 140,
            "color" : -100000,
            "alignment" : "top_center",
            "texts" : [" "]
        },
        
        "background":
        {
            "image" : "skyforgemenu:textures/background.png"
            
            
        }
 
    }
}
```

Log
```

[11:06:13] [Client thread/WARN]: Failed to load texture: skyforgemenu:textures/background.png
java.io.FileNotFoundException: skyforgemenu:textures/background.png
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:69) ~[bxi.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[bwa.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67) [bwf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:42) [bwf.class:?]
	at lumien.custommainmenu.lib.textures.TextureResourceLocation.bind(TextureResourceLocation.java:16) [TextureResourceLocation.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:307) [GuiCustom.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) [bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[11:06:13] [Client thread/WARN]: Failed to load texture: skyforgemenu:textures/skyforgethunder.png
java.io.FileNotFoundException: skyforgemenu:textures/skyforgethunder.png
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:69) ~[bxi.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[bwa.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67) [bwf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:42) [bwf.class:?]
	at lumien.custommainmenu.lib.textures.TextureResourceLocation.bind(TextureResourceLocation.java:16) [TextureResourceLocation.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:363) [GuiCustom.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) [bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[11:06:13] [Client thread/WARN]: Failed to load texture: skyforgemenu:textures/transparent.png
java.io.FileNotFoundException: skyforgemenu:textures/transparent.png
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:69) ~[bxi.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[bwa.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67) [bwf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:42) [bwf.class:?]
	at lumien.custommainmenu.lib.textures.TextureResourceLocation.bind(TextureResourceLocation.java:16) [TextureResourceLocation.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:363) [GuiCustom.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) [bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[11:06:13] [Client thread/WARN]: Failed to load texture: skyforgemenu:textures/blank.png
java.io.FileNotFoundException: skyforgemenu:textures/blank.png
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:69) ~[bxi.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[bwa.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67) [bwf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:42) [bwf.class:?]
	at lumien.custommainmenu.lib.textures.TextureResourceLocation.bind(TextureResourceLocation.java:16) [TextureResourceLocation.class:?]
	at lumien.custommainmenu.gui.GuiCustomButton.func_146112_a(GuiCustomButton.java:85) [GuiCustomButton.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:398) [GuiCustom.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) [bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[11:06:23] [Client thread/INFO]: Checking Doc Versions
```

**Comment by TimeLadyAboutTime** [comment]
UPDATE:
I just discovered that MatterOverdrive or one of it dependencies(ShadowMC/Forgelin/TESLA) is causing the problem, I don't know if their side fault or not, But I still really want this mod on the pack. I would love other solution that is not removing the mod.

**Comment by TimeLadyAboutTime** [comment]
UPDATE:
Already solved.

**Comment by anagram3k** [comment]
@TimeLadyAboutTime How did you solve it? I am having the same problem on a modpack.
