### ISSUE TITLE
Error to load Config File

### ISSUE THREAD

**Issue by ghostlyvc** [lumien231/Custom-Main-Menu#239]
So I am able to configure the logo and Title but whenever I try to link it to my own resource it comes up with that error.  I am using a mod that has its own custom main menu andI think that might be trying to take priority however it does come with the vanilla minecraft menu when I load CMM.

Is there a way to fix this or bypass that it is trying to keep the old lang files.

[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at lumien.custommainmenu.configuration.GuiConfig.loadTexts(GuiConfig.java:283)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at lumien.custommainmenu.configuration.GuiConfig.load(GuiConfig.java:104)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at lumien.custommainmenu.configuration.ConfigurationLoader.load(ConfigurationLoader.java:95)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at lumien.custommainmenu.CustomMainMenu.reload(CustomMainMenu.java:93)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at lumien.custommainmenu.lib.actions.ActionRefresh.perform(ActionRefresh.java:16)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at lumien.custommainmenu.gui.GuiCustom.func_146284_a(GuiCustom.java:736)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at lumien.custommainmenu.gui.GuiCustom.func_73864_a(GuiCustom.java:254)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[11:02:27] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[11:02:27] [Client thread/ERROR]: Error while loading new config file, trying to keep the old one loaded.

**Comment by X00LA** [comment]
You have an failure in your config file. When you edit your file and reload and the file can't beloaded you definetly have a failure.
Look for missing "," or "}" this are very often the missing peace!
