### ISSUE TITLE
Game Crash on start up can someone help?

### ISSUE THREAD

**Issue by FussyTunic30** [lumien231/Custom-Main-Menu#247]
It worked previously, i then added hoverSound and pressSound. it crashed when i added them, so i removed them. yet it still crashes.

# **EDIT: I realize i should put my crash report in this post. scroll to the bottom for the crash report ↓**

Here is my code:

{
    "images":
    {
        "title":
        {
            "image" : "custommainmenu:textures/gui/minecraft.png",
            "posX" : -137,
            "posY" : 30,
            "width" : 512,
            "height" : 512,
            "alignment" : "top_center"
        }
    },

    "buttons":
    {
        "singleplayer":
        {
            "text" : "Play Alone",
            "posX" : -280,
            "posY" : 25,
            "width" : 200,
            "height" : 24,
            "imageWidth" : 480,
            "imageHeight" : 96,
            "texture" : "modpack:textures/button.png",
            "action" :
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            },

        },

        "multiplayer":
        {
            "text" : "Play Online",
            "posX" : -280,
            "posY" : 60,
            "width" : 200,
            "height" : 24,
            "imageWidth" : 480,
            "imageHeight" : 96,
            "texture" : "modpack:textures/button.png",
            "action" :
            {
                "type" : "connectToServer",
                "ip" : "us.mineplex.com"
            }
        },

        "visit":
        {
            "text": "Visit Mr_RubyGaming",
            "posX": -280,
            "posY" : 130,
            "width" : 200,
            "height" : 24,
            "imageWidth" : 480,
            "imageHeight" : 96,
            "texture" : "modpack:textures/button.png",
            "action" :
            {
                "type": "openLink",
                "link" : "https://www.youtube.com/channel/UCrAZTzjgDZWS-KayWWDS9pg"
            }
        },

        "mods":
        {
            "text" : "Mods",
            "posX" : -280,
            "posY" : 95,
            "width" : 200,
            "height" : 24,
            "imageWidth" : 480,
            "imageHeight" : 96,
            "texture" : "modpack:textures/button.png",
            "action" :
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },

        "options":
        {
            "text" : "",
            "posX" : 280,
            "posY" : 265,
            "width" : 30,
            "height" : 30,
            "imageWidth" : 240,
            "imageHeight" : 240,
            "texture" : "modpack:textures/settings.png",
            "action":
            {
            	"type": "openGui",
            	"gui": "options",
            }
        },

        "quit":
        {
            "text" : "menu.quit",
            "posX" : -225,
            "posY" : 165,
            "width" : 98,
            "height" : 20,
            "imageWidth" : 480,
            "imageHeight" : 96,
            "texture" : "modpack:textures/button.png",
            "action" :
            {
                "type" : "quit"
            }
        },

        "language":
        {
          "text" : "",
          "posX" : -310,
          "posY" : 265,
          "width": 30,
          "height" : 30,
          "imageWidth" : 240,
          "imageHeight" : 240,
          "texture" : "modpack:textures/languages.png",
          "action":
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },

        "refresh":
        {
            "text" : "",
            "posX" : -320,
            "posY" : -100,
            "width" : 20,
            "height" : 20,
            "texture" : "custommainmenu:textures/gui/buttons.png",
            "action" :
            {
                "type" : "refresh"
    },

    "texts":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right"
        },

        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -50,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },

    "other":
    {
        "splash-text":
        {
            "posX" : 90,
            "posY" : 70,
            "color" : -256,
            "alignment" : "top_center",
            "texts" : "file:minecraft:texts/splashes.txt"
        },

        "panorama":
        {
            "images" : "minecraft:textures/gui/title/background/panorama_%c.png",
            "animate" : true,
            "animationSpeed" : 1,
            "blur" : true,
            "gradient" : true
        }
    }
}

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  LoadingPlugin (Quark-r1.4-120.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 1/18/18 3:44 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Custom Main Menu (custommainmenu)
Caused by: java.lang.RuntimeException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 34 column 10 path $.buttons.singleplayer.pressSound
	at lumien.custommainmenu.CustomMainMenu.preInit(CustomMainMenu.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 34 column 10 path $.buttons.singleplayer.pressSound
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at lumien.custommainmenu.configuration.ConfigurationLoader.load(ConfigurationLoader.java:92)
	at lumien.custommainmenu.CustomMainMenu.preInit(CustomMainMenu.java:66)
	... 41 more
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 34 column 10 path $.buttons.singleplayer.pressSound
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:505)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 505145008 bytes (481 MB) / 771751936 bytes (736 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version                     | Source                            | Signature                                |
	|:----- |:----------------- |:--------------------------- |:--------------------------------- |:---------------------------------------- |
	| UCH   | minecraft         | 1.12.2                      | minecraft.jar                     | None                                     |
	| UCH   | mcp               | 9.42                        | minecraft.jar                     | None                                     |
	| UCH   | FML               | 8.0.99.99                   | forge-1.12.2-14.23.1.2555.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge             | 14.23.1.2555                | forge-1.12.2-14.23.1.2555.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | mercurius_updater | 1.0                         | MercuriusUpdater-1.12.2.jar       | None                                     |
	| UCH   | ambience          | GRADLE:VERSION-GRADLE:BUILD | Ambience 1.1-10.jar               | None                                     |
	| UCH   | quark             | r1.4-120                    | Quark-r1.4-120.jar                | None                                     |
	| UCH   | autoreglib        | 1.3-15                      | AutoRegLib-1.3-15.jar             | None                                     |
	| UCE   | custommainmenu    | 2.0.8                       | CustomMainMenu-MC1.12.2-2.0.8.jar | None                                     |
	| UCH   | resourceloader    | 1.5.3                       | ResourceLoader-MC1.12.1-1.5.3.jar | d72e0dd57935b3e9476212aea0c0df352dd76291 |

	Loaded coremods (and transformers): 
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
LoadingPlugin (Quark-r1.4-120.jar)
  vazkii.quark.base.asm.ClassTransformer`

**Comment by luukd1** [comment]
This should fix it:

{
"images":
{
"title":
{
"image" : "custommainmenu:textures/gui/minecraft.png",
"posX" : -137,
"posY" : 30,
"width" : 512,
"height" : 512,
"alignment" : "top_center"
}
},

"buttons":
{
    "singleplayer":
    {
        "text" : "Play Alone",
        "posX" : -280,
        "posY" : 25,
        "width" : 200,
        "height" : 24,
        "imageWidth" : 480,
        "imageHeight" : 96,
        "texture" : "modpack:textures/button.png",
        "action" :
        {
            "type" : "openGui",
            "gui" : "singleplayer"
        }

    },

    "multiplayer":
    {
        "text" : "Play Online",
        "posX" : -280,
        "posY" : 60,
        "width" : 200,
        "height" : 24,
        "imageWidth" : 480,
        "imageHeight" : 96,
        "texture" : "modpack:textures/button.png",
        "action" :
        {
            "type" : "connectToServer",
            "ip" : "us.mineplex.com"
        }
    },

    "visit":
    {
        "text": "Visit Mr_RubyGaming",
        "posX": -280,
        "posY" : 130,
        "width" : 200,
        "height" : 24,
        "imageWidth" : 480,
        "imageHeight" : 96,
        "texture" : "modpack:textures/button.png",
        "action" :
        {
            "type": "openLink",
            "link" : "https://www.youtube.com/channel/UCrAZTzjgDZWS-KayWWDS9pg"
        }
    },

    "mods":
    {
        "text" : "Mods",
        "posX" : -280,
        "posY" : 95,
        "width" : 200,
        "height" : 24,
        "imageWidth" : 480,
        "imageHeight" : 96,
        "texture" : "modpack:textures/button.png",
        "action" :
        {
            "type" : "openGui",
            "gui" : "mods"
        }
    },

    "options":
    {
        "text" : "",
        "posX" : 280,
        "posY" : 265,
        "width" : 30,
        "height" : 30,
        "imageWidth" : 240,
        "imageHeight" : 240,
        "texture" : "modpack:textures/settings.png",
        "action":
        {
        	"type": "openGui",
        	"gui": "options",
        }
    },

    "quit":
    {
        "text" : "menu.quit",
        "posX" : -225,
        "posY" : 165,
        "width" : 98,
        "height" : 20,
        "imageWidth" : 480,
        "imageHeight" : 96,
        "texture" : "modpack:textures/button.png",
        "action" :
        {
            "type" : "quit"
        }
    },

    "language":
    {
      "text" : "",
      "posX" : -310,
      "posY" : 265,
      "width": 30,
      "height" : 30,
      "imageWidth" : 240,
      "imageHeight" : 240,
      "texture" : "modpack:textures/languages.png",
      "action":
        {
            "type" : "openGui",
            "gui" : "languages"
        }
    },

    "refresh":
    {
        "text" : "",
        "posX" : -320,
        "posY" : -100,
        "width" : 20,
        "height" : 20,
        "texture" : "custommainmenu:textures/gui/buttons.png",
        "action" :
        {
            "type" : "refresh"
},

"texts":
{
    "mojang":
    {
        "text" : "Copyright Mojang AB. Do not distribute!",
        "posX" : -197,
        "posY" : -10,
        "color" : -1,
        "alignment" : "bottom_right"
    },

    "fml":
    {
        "text" : "",
        "posX" : 2,
        "posY" : -50,
        "color" : -1,
        "alignment" : "bottom_left"
    }
},

"other":
{
    "splash-text":
    {
        "posX" : 90,
        "posY" : 70,
        "color" : -256,
        "alignment" : "top_center",
        "texts" : "file:minecraft:texts/splashes.txt"
    },

    "panorama":
    {
        "images" : "minecraft:textures/gui/title/background/panorama_%c.png",
        "animate" : true,
        "animationSpeed" : 1,
        "blur" : true,
        "gradient" : true
    }
}
}

**Comment by FussyTunic30** [comment]
Hey, I replaced my code with yours, and now i get this crash report :/

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  LoadingPlugin (Quark-r1.4-120.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 1/19/18 11:00 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Custom Main Menu (custommainmenu)
Caused by: java.lang.RuntimeException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 100 column 6 path $.buttons.options.action.gui
	at lumien.custommainmenu.CustomMainMenu.preInit(CustomMainMenu.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 100 column 6 path $.buttons.options.action.gui
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at lumien.custommainmenu.configuration.ConfigurationLoader.load(ConfigurationLoader.java:92)
	at lumien.custommainmenu.CustomMainMenu.preInit(CustomMainMenu.java:66)
	... 41 more
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 100 column 6 path $.buttons.options.action.gui
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:505)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 44 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 928511168 bytes (885 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version                     | Source                            | Signature                                |
	|:----- |:----------------- |:--------------------------- |:--------------------------------- |:---------------------------------------- |
	| UCH   | minecraft         | 1.12.2                      | minecraft.jar                     | None                                     |
	| UCH   | mcp               | 9.42                        | minecraft.jar                     | None                                     |
	| UCH   | FML               | 8.0.99.99                   | forge-1.12.2-14.23.1.2555.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge             | 14.23.1.2555                | forge-1.12.2-14.23.1.2555.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | mercurius_updater | 1.0                         | MercuriusUpdater-1.12.2.jar       | None                                     |
	| UCH   | ambience          | GRADLE:VERSION-GRADLE:BUILD | Ambience 1.1-10.jar               | None                                     |
	| UCH   | quark             | r1.4-120                    | Quark-r1.4-120.jar                | None                                     |
	| UCH   | autoreglib        | 1.3-15                      | AutoRegLib-1.3-15.jar             | None                                     |
	| UCE   | custommainmenu    | 2.0.8                       | CustomMainMenu-MC1.12.2-2.0.8.jar | None                                     |
	| UCH   | resourceloader    | 1.5.3                       | ResourceLoader-MC1.12.1-1.5.3.jar | d72e0dd57935b3e9476212aea0c0df352dd76291 |

	Loaded coremods (and transformers): 
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
LoadingPlugin (Quark-r1.4-120.jar)
  vazkii.quark.base.asm.ClassTransformer

**Comment by X00LA** [comment]
It looks like that you have several errors in your code.
Please post your code on [Pastebin](https://pastebin.com) and post the link here.
I will take a look into it and would see that I can help you.

**Comment by jredfox** [comment]
Caused by: java.lang.RuntimeException: com.google.gson.JsonSyntaxException: 

Says it all this is a config problem. You didn't give us the right json you actually were crashing on. Also make sure all file locations exists or you might get crashes as well.

if you use https://jsoneditoronline.org and it still is happening and you can prove all images exist in path this is a bug
