### ISSUE TITLE
"Failed to load texture" Issue

### ISSUE THREAD

**Issue by Dragennd** [lumien231/Custom-Main-Menu#281]
So I've been trying to setup the Custom Main Menu mod to change the appearance of the front of the client for a modpack I'm attempting to make. I installed both that mod and the Resource Loader mod to allow me to use my own images in for the main menu. Below is a code snippet that I pulled from the json file I edited. I didn't change anything in the file except for line 6 which defines the location of the image. Everything else in the file is the default that was there when I installed the Custom Main Menu mod.

`
        "title":
        {
            "image" : "mainmenu:textures/header.png",
            "posX" : -137,
            "posY" : 30,
            "width" : 512,
            "height" : 512,
            "alignment" : "top_center"
        },
`

After running everything with the new images in place I hit the refresh button and it now gives me the following error in the log files for the client.

`[01:00:38] [main/WARN] [net.minecraft.client.renderer.texture.TextureManager]: Failed to load texture: mainmenu:textures/header.png
java.io.FileNotFoundException: mainmenu:textures/header.png
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:69) ~[cev.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[cdm.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:69) [cdr.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:44) [cdr.class:?]
	at lumien.custommainmenu.lib.textures.TextureResourceLocation.bind(TextureResourceLocation.java:16) [TextureResourceLocation.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:399) [GuiCustom.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`

I entered everything exactly as it was shown both on the Curseforge page and what was on the original file that was created when I installed the Custom Main Menu mod. I've double and triple checked spelling and case (everything is lowercase) so I'm not really sure what's wrong. As best I can tell it keeps trying to pull from another location even tho I have it set to look in the folder specified above and refuses to look elsewhere. I have another file I tried to use as the background in a different part of the json file, a jpg, the code of which I copied from the FTB Revelation Custom Main Menu json file and it gave me the same error so I'm truly at a loss here and could really use some help.

The following is a screenshot of the file structure for my current setup. The image I'm trying to use is header.png.
![image_1](https://user-images.githubusercontent.com/39970215/41003505-9445e8f4-68dc-11e8-9ff2-ae6cbe91282d.png)

**Comment by lumien231** [comment]
Could you create a folder called "debug" in your resources folder run mc and post your debug log here?

**Comment by Dragennd** [comment]
Believe I figured out the problem. The mod can't load images that weren't in the folder at launch. I restarted the client and it showed the images that were in the resources/textures folder but won't load an image I inserted into the folder after the client was loaded. Seems I need to have all the images I want to use in the folder before I launch the client and then I can manipulate their positions as needed.

**Comment by signalm** [comment]
I'm still having this issue could you please help me

**Comment by Xiang990293** [comment]
Same issue here for making gui, and reloading textures can simply F3+T after build the project?

**Comment by Xelbayria** [comment]
I have the same issue. I can't find the cause. The Path of the textures are correct and It seems the TextureManager won't load the texture for GUI. But the block's front using the same texture is actually being loaded just fine. This make no sense...

I'm researching to find out what's going on. If anyone have more information on what's wrong. I appreciate the information being shared.

**Comment by angelgabrielakecatzin-gif** [comment]
Help me, bro.
