### ISSUE TITLE
Images not loading in 1.12.2

### ISSUE THREAD

**Issue by Wizardon777** [lumien231/Custom-Main-Menu#299]
**Forge version:** 1.12.2-14.23.4.2756
**CMM version:** CustomMainMenu-MC1.12.2-2.0.8
**RL version:** ResourceLoader-MC1.12.1-1.5.3

as I stated in the title, I'm unable to load any images, only getting the "missing texture" pink-black thingy...

I have another 1.12.2 pack, and everything works great on it. what did I do wrong this time?

**Included files:**
![files](https://user-images.githubusercontent.com/22551232/44244199-6ccbb780-a1db-11e8-94ce-dab72128af91.png)
![menu](https://user-images.githubusercontent.com/22551232/44244200-6d644e00-a1db-11e8-96fd-e84f9ba4eb9d.png)
[mainmenu.json.txt](https://github.com/lumien231/Custom-Main-Menu/files/2295752/mainmenu.json.txt)
_(changed the json file into txt for uploading here)_

**Comment by syorito-hatsuki** [comment]
Reload Minecraft

**Comment by Wizardon777** [comment]
Yeah, tried that...

also tried:
re-installing CMM and RL
re-creating the config file
changing folder and file names
removing all other mods (maybe they were interfering)
computer reboot
twitch re-installation

anything else I haven't tried?

**Comment by Shtopm** [comment]
You should put image in jar file of mod

**Comment by Shtopm** [comment]
in assets/custommainmenu/textures

**Comment by Ronnie0982** [comment]
Well you need to link the path to the image in the config file

**Comment by Wizardon777** [comment]
never mind, the mod developer seems to be uninterested in helping users, I've found my own solution, thank you all for trying to help...

**Comment by FuriousG** [comment]
Hey, I have the same issue, Can you Wizardon777 tell me how you fixed it?

**Comment by syorito-hatsuki** [comment]
> Hey, I have the same issue, Can you Wizardon777 tell me how you fixed it?

Show u config of custommainmenu

**Comment by FuriousG** [comment]
Ok

**Comment by FuriousG** [comment]
{
"images":
{

    "title":
    {
        "image" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/minecraft.png",
        "posX" : -450,
        "posY" : -50,
        "width" : 720,
        "height" : 720,
        "alignment" : "right_center"
    },
    
    "edition":
    {
        "image" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/edition.png",
        "posX" : -325,
        "posY" : 5,
        "width" : 165,
        "height" : 21,
        "alignment" : "right_center"
    }
},
"buttons":
{
"singleplayer":
{
"text" : "menu.singleplayer",
"normalTextColor" : 12303291,
"hoverTextColor" : 3125670,
"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
"posX" : 97,
"posY" : -100,
"width" : 196,
"height" : 30,
imageWidth : 100,
imageHeight : 50,
"alignment" : "left_center",
"action" :
{
"type" : "openGui",
"gui" : "singleplayer"
}
},

	"multiplayer":
    {
        "text" : "menu.multiplayer",			
		"normalTextColor" : 12303291,
		"hoverTextColor" : 3125670,
		"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
        "posX" : 97,
        "posY" : -65,
        "width" : 196,
        "height" : 30,
		imageWidth : 100,
		imageHeight : 50,
		"alignment" : "left_center",
        "action" : 
        {
            "type" : "openGui",
            "gui" : "multiplayer"
        }
    },
           
	"options":
    {
        "text" : "menu.options",
		"normalTextColor" : 12303291,
		"hoverTextColor" : 3125670,
		"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
        "posX" : 97,
        "posY" : -30,
        "width" : 196,
        "height" : 25,
		imageWidth : 100,
		imageHeight : 50,
		"alignment" : "left_center",
        "action" : 
        {
            "type" : "openGui",
            "gui" : "options"
        }
    },
	        
	"language":
    {
        "text" : "options.language",
		"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
        "posX" : 97,
        "posY" : 0,
        "width" : 196,
        "height" : 25,
		imageWidth : 100,
		imageHeight : 50,			
		"alignment" : "left_center",
        "action" : 
        {
            "type" : "openGui",
            "gui" : "languages"
        }
    },
                
    "quit":
    {
        "text" : "menu.quit",
		"normalTextColor" : 16729156,
		"hoverTextColor" : 14483456,
		"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
        "posX" : 97,
        "posY" : 65,
        "width" : 196,
        "height" : 25,
		imageWidth : 100,
		imageHeight : 50,
		"alignment" : "left_center",
		"hoverText" : "No! Don't leave!",
        "action" : 
        {
            "type" : "quit"
        }
    },
	
    "mods":
    {
        "text" : "Mods (#modsloaded#/#modsactive#)",
		"normalTextColor" : 6710886,
		"hoverTextColor" : 3125670,
		"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
        "posX" : 97,
        "posY" : 30,
        "width" : 196,
        "height" : 25,
		imageWidth : 100,
		imageHeight : 50,
		"alignment" : "left_center",
        "action" : 
        {
            "type" : "openGui",
            "gui" : "mods"
        }

    }
},

"labels":
{
    "mojang":
    {
        "text" : "Copyright Mojang AB. Do not distribute!",
        "hoverText" : "§nCopyright Mojang AB. Do not distribute!",
        "posX" : -197,
        "posY" : -10,
        "color" : -1,
        "alignment" : "bottom_right",
        "action" : 
        {
            "type" : "openGui",
            "gui" : "credits"
        }
    },
    
    "fml":
    {
        "text" : "",
        "posX" : 2,
        "posY" : -45,
        "color" : -1,
        "alignment" : "bottom_left"
    }
},

"other":
{
    "splash-text":
    {
        "posX" : -118,
        "posY" : 5,
        "color" : -256,
        "alignment" : "right_center",
        "texts" : "file:minecraft:texts/splashes.txt"
    },
    
    "background":
    {
        "image" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/menubackground.png",
        "mode" : "fill"
    }
}

> > Hey, I have the same issue, Can you Wizardon777 tell me how you fixed it?
> 
> Show u config of custommainmenu

**Comment by syorito-hatsuki** [comment]
> {
> "images":
> {
> 
> ```
> "title":
> {
>     "image" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/minecraft.png",
>     "posX" : -450,
>     "posY" : -50,
>     "width" : 720,
>     "height" : 720,
>     "alignment" : "right_center"
> },
> 
> "edition":
> {
>     "image" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/edition.png",
>     "posX" : -325,
>     "posY" : 5,
>     "width" : 165,
>     "height" : 21,
>     "alignment" : "right_center"
> }
> ```
> 
> },
> "buttons":
> {
> "singleplayer":
> {
> "text" : "menu.singleplayer",
> "normalTextColor" : 12303291,
> "hoverTextColor" : 3125670,
> "texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
> "posX" : 97,
> "posY" : -100,
> "width" : 196,
> "height" : 30,
> imageWidth : 100,
> imageHeight : 50,
> "alignment" : "left_center",
> "action" :
> {
> "type" : "openGui",
> "gui" : "singleplayer"
> }
> },
> 
> ```
> "multiplayer":
> {
>     "text" : "menu.multiplayer",			
> 	"normalTextColor" : 12303291,
> 	"hoverTextColor" : 3125670,
> 	"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
>     "posX" : 97,
>     "posY" : -65,
>     "width" : 196,
>     "height" : 30,
> 	imageWidth : 100,
> 	imageHeight : 50,
> 	"alignment" : "left_center",
>     "action" : 
>     {
>         "type" : "openGui",
>         "gui" : "multiplayer"
>     }
> },
>        
> "options":
> {
>     "text" : "menu.options",
> 	"normalTextColor" : 12303291,
> 	"hoverTextColor" : 3125670,
> 	"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
>     "posX" : 97,
>     "posY" : -30,
>     "width" : 196,
>     "height" : 25,
> 	imageWidth : 100,
> 	imageHeight : 50,
> 	"alignment" : "left_center",
>     "action" : 
>     {
>         "type" : "openGui",
>         "gui" : "options"
>     }
> },
>         
> "language":
> {
>     "text" : "options.language",
> 	"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
>     "posX" : 97,
>     "posY" : 0,
>     "width" : 196,
>     "height" : 25,
> 	imageWidth : 100,
> 	imageHeight : 50,			
> 	"alignment" : "left_center",
>     "action" : 
>     {
>         "type" : "openGui",
>         "gui" : "languages"
>     }
> },
>             
> "quit":
> {
>     "text" : "menu.quit",
> 	"normalTextColor" : 16729156,
> 	"hoverTextColor" : 14483456,
> 	"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
>     "posX" : 97,
>     "posY" : 65,
>     "width" : 196,
>     "height" : 25,
> 	imageWidth : 100,
> 	imageHeight : 50,
> 	"alignment" : "left_center",
> 	"hoverText" : "No! Don't leave!",
>     "action" : 
>     {
>         "type" : "quit"
>     }
> },
> 
> "mods":
> {
>     "text" : "Mods (#modsloaded#/#modsactive#)",
> 	"normalTextColor" : 6710886,
> 	"hoverTextColor" : 3125670,
> 	"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
>     "posX" : 97,
>     "posY" : 30,
>     "width" : 196,
>     "height" : 25,
> 	imageWidth : 100,
> 	imageHeight : 50,
> 	"alignment" : "left_center",
>     "action" : 
>     {
>         "type" : "openGui",
>         "gui" : "mods"
>     }
> 
> }
> ```
> 
> },
> 
> "labels":
> {
> "mojang":
> {
> "text" : "Copyright Mojang AB. Do not distribute!",
> "hoverText" : "§nCopyright Mojang AB. Do not distribute!",
> "posX" : -197,
> "posY" : -10,
> "color" : -1,
> "alignment" : "bottom_right",
> "action" :
> {
> "type" : "openGui",
> "gui" : "credits"
> }
> },
> 
> ```
> "fml":
> {
>     "text" : "",
>     "posX" : 2,
>     "posY" : -45,
>     "color" : -1,
>     "alignment" : "bottom_left"
> }
> ```
> 
> },
> 
> "other":
> {
> "splash-text":
> {
> "posX" : -118,
> "posY" : 5,
> "color" : -256,
> "alignment" : "right_center",
> "texts" : "file:minecraft:texts/splashes.txt"
> },
> 
> ```
> "background":
> {
>     "image" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/menubackground.png",
>     "mode" : "fill"
> }
> ```
> 
> }

edit like a big code block using
\`\`\`json
//code here
\`\`\`

**Comment by FuriousG** [comment]
```{
"images":
{

"title":
{
    "image" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/minecraft.png",
    "posX" : -450,
    "posY" : -50,
    "width" : 720,
    "height" : 720,
    "alignment" : "right_center"
},

"edition":
{
    "image" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/edition.png",
    "posX" : -325,
    "posY" : 5,
    "width" : 165,
    "height" : 21,
    "alignment" : "right_center"
}
},
"buttons":
{
"singleplayer":
{
"text" : "menu.singleplayer",
"normalTextColor" : 12303291,
"hoverTextColor" : 3125670,
"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
"posX" : 97,
"posY" : -100,
"width" : 196,
"height" : 30,
imageWidth : 100,
imageHeight : 50,
"alignment" : "left_center",
"action" :
{
"type" : "openGui",
"gui" : "singleplayer"
}
},

"multiplayer":
{
    "text" : "menu.multiplayer",			
	"normalTextColor" : 12303291,
	"hoverTextColor" : 3125670,
	"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
    "posX" : 97,
    "posY" : -65,
    "width" : 196,
    "height" : 30,
	imageWidth : 100,
	imageHeight : 50,
	"alignment" : "left_center",
    "action" : 
    {
        "type" : "openGui",
        "gui" : "multiplayer"
    }
},
       
"options":
{
    "text" : "menu.options",
	"normalTextColor" : 12303291,
	"hoverTextColor" : 3125670,
	"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
    "posX" : 97,
    "posY" : -30,
    "width" : 196,
    "height" : 25,
	imageWidth : 100,
	imageHeight : 50,
	"alignment" : "left_center",
    "action" : 
    {
        "type" : "openGui",
        "gui" : "options"
    }
},
        
"language":
{
    "text" : "options.language",
	"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
    "posX" : 97,
    "posY" : 0,
    "width" : 196,
    "height" : 25,
	imageWidth : 100,
	imageHeight : 50,			
	"alignment" : "left_center",
    "action" : 
    {
        "type" : "openGui",
        "gui" : "languages"
    }
},
            
"quit":
{
    "text" : "menu.quit",
	"normalTextColor" : 16729156,
	"hoverTextColor" : 14483456,
	"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
    "posX" : 97,
    "posY" : 65,
    "width" : 196,
    "height" : 25,
	imageWidth : 100,
	imageHeight : 50,
	"alignment" : "left_center",
	"hoverText" : "No! Don't leave!",
    "action" : 
    {
        "type" : "quit"
    }
},

"mods":
{
    "text" : "Mods (#modsloaded#/#modsactive#)",
	"normalTextColor" : 6710886,
	"hoverTextColor" : 3125670,
	"texture" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/btn.png",
    "posX" : 97,
    "posY" : 30,
    "width" : 196,
    "height" : 25,
	imageWidth : 100,
	imageHeight : 50,
	"alignment" : "left_center",
    "action" : 
    {
        "type" : "openGui",
        "gui" : "mods"
    }

}
},

"labels":
{
"mojang":
{
"text" : "Copyright Mojang AB. Do not distribute!",
"hoverText" : "§nCopyright Mojang AB. Do not distribute!",
"posX" : -197,
"posY" : -10,
"color" : -1,
"alignment" : "bottom_right",
"action" :
{
"type" : "openGui",
"gui" : "credits"
}
},

"fml":
{
    "text" : "",
    "posX" : 2,
    "posY" : -45,
    "color" : -1,
    "alignment" : "bottom_left"
}
},

"other":
{
"splash-text":
{
"posX" : -118,
"posY" : 5,
"color" : -256,
"alignment" : "right_center",
"texts" : "file:minecraft:texts/splashes.txt"
},

"background":
{
    "image" : "C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/menubackground.png",
    "mode" : "fill"
}
}```

**Comment by syorito-hatsuki** [comment]
U need to use resource loader for custom images
```json
"background":
{
    "image" : "MainMenu:textures/menubackground.png",
    "mode" : "fill"
}
```
Like this (If I remember correct pathing)

**Comment by FuriousG** [comment]
So I replace all the C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/menubackground.png to MainMenu:textures/menubackground.png (but with different png's)

**Comment by syorito-hatsuki** [comment]
> So I replace all the C:/Users/grays/Downloads/mmc-stable-win32/MultiMC/instances/CustomMainMenu/.minecraft/resources/MainMenu/textures/menubackground.png to MainMenu:textures/menubackground.png (but with different png's)

Yes. U didn't need full path. Minecraft not have access to u system folder. As root is work resource folder and as modname first folders

**Comment by FuriousG** [comment]
Oh ok, thanks!

**Comment by FuriousG** [comment]
Hmmm, It didn't seem to work?
![image](https://user-images.githubusercontent.com/82079549/113824054-52a8c400-974d-11eb-97b0-8119e23f1f0d.png)

**Comment by FuriousG** [comment]
I'm still getting the missing tectures

**Comment by syorito-hatsuki** [comment]
> Hmmm, It didn't seem to work?
> ![image](https://user-images.githubusercontent.com/82079549/113824054-52a8c400-974d-11eb-97b0-8119e23f1f0d.png)

what logs say?

**Comment by FuriousG** [comment]
It says....
```java.io.FileNotFoundException: mainmenu:textures/menubackground.png
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:69) ~[cev.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[cdm.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:69) [cdr.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:44) [cdr.class:?]
	at lumien.custommainmenu.lib.textures.TextureResourceLocation.bind(TextureResourceLocation.java:16) [TextureResourceLocation.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:343) [GuiCustom.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[02:58:39] [Client thread/WARN] [minecraft/TextureManager]: Failed to load texture: mainmenu:textures/minecraft.png
java.io.FileNotFoundException: mainmenu:textures/minecraft.png
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:69) ~[cev.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[cdm.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:69) [cdr.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:44) [cdr.class:?]
	at lumien.custommainmenu.lib.textures.TextureResourceLocation.bind(TextureResourceLocation.java:16) [TextureResourceLocation.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:399) [GuiCustom.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[02:58:39] [Client thread/WARN] [minecraft/TextureManager]: Failed to load texture: mainmenu:textures/edition.png
java.io.FileNotFoundException: mainmenu:textures/edition.png
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:69) ~[cev.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[cdm.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:69) [cdr.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:44) [cdr.class:?]
	at lumien.custommainmenu.lib.textures.TextureResourceLocation.bind(TextureResourceLocation.java:16) [TextureResourceLocation.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:399) [GuiCustom.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[02:58:39] [Client thread/WARN] [minecraft/TextureManager]: Failed to load texture: mainmenu:textures/btn.png
java.io.FileNotFoundException: mainmenu:textures/btn.png
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:69) ~[cev.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[cdm.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:69) [cdr.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:44) [cdr.class:?]
	at lumien.custommainmenu.lib.textures.TextureResourceLocation.bind(TextureResourceLocation.java:16) [TextureResourceLocation.class:?]
	at lumien.custommainmenu.gui.GuiCustomButton.func_191745_a(GuiCustomButton.java:85) [GuiCustomButton.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:434) [GuiCustom.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by syorito-hatsuki** [comment]
Change folder name MainMenu to MainMenu. Use only lower register

**Comment by FuriousG** [comment]
What do you mean by "Use only lower register"

**Comment by syorito-hatsuki** [comment]
> What do you mean by "Use only lower register"

Don't use [A-Z] use only [a-z]

**Comment by FuriousG** [comment]
Ah ok
Ill see if this works

**Comment by FuriousG** [comment]
It works! But the Minecraft logo is Waayyy to big which I can fix so thanks for helping and goodbye!

**Comment by FuriousG** [comment]
And again thank you! You really really helped me out a lot

**Comment by syorito-hatsuki** [comment]
> And again thank you! You really really helped me out a lot

Next time read examples by author on curseforge

**Comment by FuriousG** [comment]
Ok!
