### ISSUE TITLE
Crash on startup (1.7.10)

### ISSUE THREAD

**Issue by dracoattila** [lumien231/Custom-Main-Menu#362]
The Crash Report :

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 7/20/19 11:57 AM
Description: Initializing game

java.lang.RuntimeException: java.lang.NullPointerException
	at lumien.custommainmenu.CustomMainMenu.preInit(CustomMainMenu.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NullPointerException
	at lumien.custommainmenu.configuration.GuiConfig.loadTexts(GuiConfig.java:283)
	at lumien.custommainmenu.configuration.GuiConfig.load(GuiConfig.java:104)
	at lumien.custommainmenu.configuration.ConfigurationLoader.load(ConfigurationLoader.java:95)
	at lumien.custommainmenu.CustomMainMenu.preInit(CustomMainMenu.java:67)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at lumien.custommainmenu.CustomMainMenu.preInit(CustomMainMenu.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1114495816 bytes (1062 MB) / 1663041536 bytes (1586 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8192m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCH	smoothfontcore{1.7.10-1.10} [Smooth Font Core] (minecraft.jar) 
	UCH	smoothfont{1.7.10-1.10} [Smooth Font] ([1.7.10] Smooth Font.jar) 
	UCH	enhancedbiomes{2.4.1 for MC 1.7.10} [Enhanced Biomes] ([1.7.10] Enhanced Biomes.jar) 
	UCH	skinport{1.7.10-v8c} [SkinPort] ([1.7.10] Skin Port.jar) 
	UCH	antiqueatlas{4.4.4} [Antique Atlas] (antiqueatlas-1.7.10-4.4.4.jar) 
	UCH	AntiqueAtlasOverlay{1.2} [Antique Atlas Overlay] (AntiqueAtlasOverlay-1.7.10-1.2.jar) 
	UCH	ATG{0.10.0} [Alternate Terrain Generation] (ATG-1.7.10-0.12.0.jar) 
	UCH	hud{1.3.5} [Better HUD] (Better+HUD+by+NukeDuck+[1.7.10][1.3.5].jar) 
	UCH	betterloadingscreen{1.3.10} [Better Loading Screen] (BetterLoadingScreen-1.3.10.jar) 
	UCH	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar) 
	UCH	climatecontrol{0.8.1} [Climate Control] (ClimateControl-0.8.2.jar) 
	UCH	customcursormod{1.2.2} [Custom Cursor Mod] (CustomCursorMod-1.2.2.jar) 
	UCE	CustomMainMenu{1.9.2} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.9.2.jar) 
	UCH	sonicvisuals{0.3} [Enhanced Visuals] (EnhancedVisuals+v0.2.4+mc1.7.10.jar) 
	UCH	ExtrabiomesXL{3.16.4} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.4.jar) 
	UCH	HardcoreDarkness{1.7} [Hardcore Darkness] (HardcoreDarkness-MC1.7.10-1.7.jar) 
	UCH	HelpFixer{1.0.7} [HelpFixer] (HelpFixer-1.0.7.jar) 
	UCH	Highlands{2.2.3} [Highlands] (Highlands-1.7.2-v-2.2.3.jar) 
	UCH	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCH	LagFix{2.0.1} [LagFix] (LagFix-2.0.1-mc1.7.10-forge.jar) 
	UCH	login_shield{1.7.10-2-gf6e21a7} [Login Shield] (Login_Shield-1.7.10-2-gf6e21a7.jar) 
	UCH	MineMenu{1.2.0} [MineMenu] (MineMenu-1.7.10-1.2.0.B44-universal.jar) 
	UCH	notenoughIDs{1.4.0} [NotEnoughIDs] (NotEnoughIDs-1.5.0prepreprepreAlpha.jar) 
	UCH	ResourceLoader{1.3} [Resource Loader] (ResourceLoader-MC1.7.10-1.3.jar) 
	UCH	RTG{1.7.10-1.1.1.7} [Realistic Terrain Generation] (RTG-1.7.10-1.1.1.7.jar) 
	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCH	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.64, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: [1.7.10] Plunder Pixel's Shaders.zip
	OpenGlVersion: 4.6.0 NVIDIA 430.64
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

The Code for Menu :

{
  "images": {
    "title": {
      "image": "custommainmenu:textures/gui/minecraft.png",
      "posX": -137,
      "posY": 30,
      "width": 512,
      "height": 512,
      "alignment": "top_center"
    }
  },
  "buttons": {
    "singleplayer": {
      "text": "menu.singleplayer",
      "posX": 0,
      "posY": 0,
      "width": 201,
      "height": 20,
      "alignment": "left_center",
      "action": {
        "type": "openGui",
        "gui": "singleplayer"
      }
    },
    "multiplayer": {
      "text": "menu.multiplayer",
      "posX": 0,
      "posY": 25,
      "width": 201,
      "height": 20,
      "alignment": "left_center",
      "hoverText": "Better together! Let's Go!",
      "action": {
        "type": "openGui",
        "gui": "multiplayer"
      }
    },
    "mods": {
      "text": "fml.menu.mods",
      "posX": 0,
      "posY": 50,
      "width": 201,
      "height": 20,
      "alignment": "left_center",
      "action": {
        "type": "openGui",
        "gui": "mods"
      }
    },
    "options": {
      "text": "menu.options",
      "posX": -200,
      "posY": 0,
      "width": 201,
      "height": 20,
      "alignment": "right_center",
      "action": {
        "type": "openGui",
        "gui": "options"
      }
    },
    "language": {
      "text": "options.language",
      "posX": -200,
      "posY": 25,
      "width": 201,
      "height": 20,
      "alignment": "right_center",
      "action": {
        "type": "openGui",
        "gui": "options"
      }
    },
    "quit": {
      "text": "menu.quit",
      "posX": -200,
      "posY": 50,
      "width": 201,
      "height": 20,
      "alignment": "right_center",
      "hoverText": "No! Don't leave!",
      "action": {
        "type": "quit"
      }
    }
  },
  "labels": {
    "mojang": {
      "text": "Copyright Mojang AB. Do not distribute!",
      "posX": 4,
      "posY": -12,
      "color": -1,
      "alignment": "bottom_left"
    },
    "modcounts": {
      "text": "Mods Loaded : #modsloaded# / Mods Active : #modsactive#",
      "posX": -150,
      "posY": -12,
      "color": -1,
      "alignment": "bottom_right"
    }
  }
}

**Comment by LevganSaxen** [comment]
up
