### ISSUE TITLE
minecraft crashes on loading

### ISSUE THREAD

**Issue by Ehrenf** [lumien231/Custom-Main-Menu#382]
here is my crash report
---- Minecraft Crash Report ----
// Don't do that.

Time: 10/11/19 11:04 AM
Description: Initializing game

java.lang.RuntimeException: java.lang.NullPointerException
	at lumien.custommainmenu.CustomMainMenu.preInit(CustomMainMenu.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at lumien.custommainmenu.configuration.GuiConfig.getStringPlease(GuiConfig.java:496)
	at lumien.custommainmenu.configuration.GuiConfig.getText(GuiConfig.java:446)
	at lumien.custommainmenu.configuration.GuiConfig.loadTexts(GuiConfig.java:291)
	at lumien.custommainmenu.configuration.GuiConfig.load(GuiConfig.java:104)
	at lumien.custommainmenu.configuration.ConfigurationLoader.load(ConfigurationLoader.java:95)
	at lumien.custommainmenu.CustomMainMenu.preInit(CustomMainMenu.java:67)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at lumien.custommainmenu.CustomMainMenu.preInit(CustomMainMenu.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 156533688 bytes (149 MB) / 269365248 bytes (256 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCH	Forge{10.13.4.1481} [Minecraft Forge] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCE	CustomMainMenu{1.9.2} [Custom Main Menu] ((client)CustomMainMenu-MC1.7.10-1.9.2.jar) 
	UCH	ResourceLoader{1.3} [Resource Loader] ((client)ResourceLoader-MC1.7.10-1.3.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 436.15' Renderer: 'GeForce RTX 2070/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1481-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 436.15, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
heres my config
{
    "images": {
        "title": {
            "image": "ehrensepicgaming:ehrensepicgamingcraft.png",
            "posX": -180,
            "posY": 30,
            "width": 372,
            "height": 64,
            "alignment": "top_center"
        },
        "button_background": {
            "image": "the_rising_world:textures/gui/TheRisingWorld_ButtonBackground.png",
            "posX": -110,
            "posY": -32,
            "alignment": "center",
            "width": 220,
            "height": 108
        }
    },
    "buttons": {
        "singleplayer": {
            "text": "menu.singleplayer",
            "posX": -100,
            "posY": -24,
            "alignment": "center",
            "width": 98,
            "height": 20
            "action" :
        },
        "multiplayer": {
            "text": "menu.multiplayer",
            "posX": 2,
            "posY": -24,
            "alignment": "center",
            "width": 98,
            "height": 20
            "action" :
        },
        "mods": {
            "text": "fml.menu.mods",
            "posX": -100,
            "posY": 0,
            "alignment": "center",
            "width": 200,
            "height": 20
            "action" :
        },
        "options": {
            "text": "menu.options",
            "posX": -100,
            "posY": 24,
            "alignment": "center",
            "width": 98,
            "height": 20
            "action" :
        },
        "quit": {
            "text": "menu.quit",
            "posX": 2,
            "posY": 24,
            "alignment": "center",
            "width": 98,
            "height": 20
            "action" :
        },
        "language": {
            "text": "",
            "posX": -22,
            "posY": 48,
            "alignment": "center",
            "width": 20,
            "height": 20
            "action" :
        },
        "refresh": {
            "text": "",
            "posX": 2,
            "posY": 48,
            "alignment": "center",
            "width": 20,
            "height": 20
            "action" :
        }
    },
    "texts": {
        "mojang": {
            "text": "Copyright Mojang AB. Do not distribute!",
            "posX": -205,
            "posY": -10,
            "color": -1,
            "alignment": "bottom_right"
    },
    "other": {
        "background": 
            {
            "image" : "ehrensepicgaming:background.png",
            "mode" : "fill"
            }
        }
    }
}

**Comment by ROMVoid95** [comment]
your missing the actions in each button, 

here i added them for you
https://hastebin.com/gefuruzaja.json

**Comment by Ehrenf** [comment]
Thanks ROMVoid95
