### ISSUE TITLE
Image Rendering as missing textures

### ISSUE THREAD

**Issue by Digital-Twilight** [lumien231/Custom-Main-Menu#433]
Hello, I've got some issues in image rendering, I did do nothing with this picture, just decompile with MCP and in Eclipse run the code.
`[Client thread/WARN]: Failed to load texture: minecraft:textures/gui/title/edition.png
java.io.FileNotFoundException: minecraft:textures/gui/title/edition.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:66) ~[bin/:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:62) ~[bin/:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SimpleTexture.java:31) ~[bin/:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:66) [bin/:?]
	at net.minecraft.client.renderer.texture.TextureManager.bindTexture(TextureManager.java:41) [bin/:?]
	at net.minecraft.client.gui.GuiMainMenu.func_73863_a(GuiMainMenu.java:498) [bin/:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1113) [bin/:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1095) [bin/:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:395) [bin/:?]
	at net.minecraft.client.main.Main.main(Main.java:115) [bin/:?]
	at Start.main(Start.java:11) [bin/:?]
`
![Снимок экрана (163)](https://user-images.githubusercontent.com/58146150/89679931-b34fda80-d8fa-11ea-8f19-3834c56242a0.png)

**Comment by Deepfried-Chips** [comment]
thatis i'm pretty sure a problem with resourceloader images with the format of .jpg work just fine

**Comment by loxchmorez** [comment]
Install any archive editor like 7z then go to the eclipse open: jars>versions>your version>urversion.jar with 7z then open assets>minecraft>textures>gui>title and paste here linked image https://www.mediafire.com/view/mcsf8slir5hxusp/edition.png/file
