### ISSUE TITLE
APNG crashes the game

### ISSUE THREAD

**Issue by forresthopkinsa** [lumien231/Custom-Main-Menu#443]
When trying to use an APNG file, I get this crash:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MovingWorldCore (movingworld-1.12-6.353-full.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  mysttmtgravitymod (UpAndDownAndAllAround-1.12.2-2.9.1.jar)
  Vertically Stacked Dimensions ASM (VerticallyStackedDimensions-1.12.2-0.1.9.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 9/22/20 10:41 PM
Description: Rendering screen

java.lang.NoClassDefFoundError: net/ellerton/japng/Png
	at lumien.custommainmenu.lib.textures.TextureApng.load(TextureApng.java:92)
	at lumien.custommainmenu.lib.textures.TextureApng.bind(TextureApng.java:55)
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:400)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.ellerton.japng.Png
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at lumien.custommainmenu.lib.textures.TextureApng.load(TextureApng.java:92)
	at lumien.custommainmenu.lib.textures.TextureApng.bind(TextureApng.java:55)
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:400)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: lumien.custommainmenu.gui.GuiCustom
	Mouse location: Scaled: (232, 250). Absolute: (464, 414)
	Screen size: Scaled: (752, 458). Absolute: (1504, 915). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.15.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2760908616 bytes (2633 MB) / 6677331968 bytes (6368 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 7 total; -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 84 mods loaded, 84 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                           | Version                  | Source                                         | Signature                                |
	|:------ |:-------------------------------------------- |:------------------------ |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                                    | 1.12.2                   | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                                          | 9.42                     | minecraft.jar                                  | None                                     |
	| LCHIJA | FML                                          | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                                        | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | com.elytradev.movingworld.common.asm.coremod |                          | minecraft.jar                                  | None                                     |
	| LCHIJA | aether_legacy                                | 1.5.2                    | aether-1.12.2-v1.5.2.jar                       | None                                     |
	| LCHIJA | antiqueatlas                                 | 4.6.3                    | antiqueatlas-1.12.2-4.6.3.jar                  | None                                     |
	| LCHIJA | antiqueatlasoverlay                          | 1.2                      | antiqueatlas-1.12.2-4.6.3.jar                  | None                                     |
	| LCHIJA | applecore                                    | 3.4.0                    | AppleCore-mc1.12.2-3.4.0.jar                   | None                                     |
	| LCHIJA | baubles                                      | 1.5.2                    | Baubles-1.12-1.5.2.jar                         | None                                     |
	| LCHIJA | astralsorcery                                | 1.10.27                  | astralsorcery-1.12.2-1.10.27.jar               | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | jei                                          | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                      | None                                     |
	| LCHIJA | quark                                        | r1.6-179                 | Quark-r1.6-179.jar                             | None                                     |
	| LCHIJA | autoreglib                                   | 1.3-32                   | AutoRegLib-1.3-32.jar                          | None                                     |
	| LCHIJA | bettercaves                                  | 1.12.2                   | bettercaves-1.12.2-2.0.4.jar                   | None                                     |
	| LCHIJA | forgelin                                     | 1.8.4                    | Forgelin-1.8.4.jar                             | None                                     |
	| LCHIJA | betterfoliage                                | 2.3.1                    | BetterFoliage-MC1.12-2.3.1.jar                 | None                                     |
	| LCHIJA | bettermineshafts                             | 1.12.2-2.1.0             | BetterMineshaftsForge-1.12.2-2.1.0.jar         | None                                     |
	| LCHIJA | biomesoplenty                                | 7.0.1.2444               | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar  | None                                     |
	| LCHIJA | blockcraftery                                | 1.12.2-1.3.1             | blockcraftery-1.12.2-1.3.1.jar                 | None                                     |
	| LCHIJA | cd4017be_lib                                 | 6.5.1                    | CD4017BE_lib-1.12.2-6.5.1.jar                  | None                                     |
	| LCHIJA | chameleon                                    | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                       | None                                     |
	| LCHIJA | codechickenlib                               | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux                                 | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar        | None                                     |
	| LCHIJA | cofhcore                                     | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar          | None                                     |
	| LCHIJA | cofhworld                                    | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar         | None                                     |
	| LCHIJA | mantle                                       | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                       | None                                     |
	| LCHIJA | tconstruct                                   | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar               | None                                     |
	| LCHIJA | conarm                                       | 1.2.5.9                  | conarm-1.12.2-1.2.5.9.jar                      | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | cookingforblockheads                         | 6.5.0                    | CookingForBlockheads_1.12.2-6.5.0.jar          | None                                     |
	| LCHIJA | corpse                                       | 1.12.2-1.0.8             | corpse-1.12.2-1.0.8.jar                        | None                                     |
	| LCHIJA | custommainmenu                               | 2.0.9.1                  | CustomMainMenu-MC1.12.2-2.0.9.1.jar            | None                                     |
	| LCHIJA | darknesslib                                  | 1.1.0                    | DarknessLib-1.12.2-1.1.0.jar                   | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | movingworld                                  | 1.12-6.353               | movingworld-1.12-6.353-full.jar                | None                                     |
	| LCHIJA | davincisvessels                              | @DVESSELSVER@            | davincisvessels-1.12-6.340-full.jar            | None                                     |
	| LCHIJA | sereneseasons                                | 1.2.18                   | SereneSeasons-1.12.2-1.2.18-universal.jar      | None                                     |
	| LCHIJA | orelib                                       | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround                                    | 3.6.1.0                  | DynamicSurroundings-1.12.2-3.6.1.0.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dynamictrees                                 | 1.12.2-0.9.14            | DynamicTrees-1.12.2-0.9.14.jar                 | None                                     |
	| LCHIJA | dynamictreesbop                              | 1.12.2-1.4.2             | DynamicTreesBOP-1.12.2-1.4.2.jar               | None                                     |
	| LCHIJA | natura                                       | 1.12.2-4.3.2.69          | natura-1.12.2-4.3.2.69.jar                     | None                                     |
	| LCHIJA | dynamictreesnatura                           | 1.12.2-1.1.2             | dynamictreesNatura-1.12.2-1.1.2.jar            | None                                     |
	| LCHIJA | harvestcraft                                 | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zg.jar                | None                                     |
	| LCHIJA | dynamictreesphc                              | 1.12.2-1.4.2             | DynamicTreesPHC-1.12.2-1.4.2.jar               | None                                     |
	| LCHIJA | dynamictreesquark                            | 1.12.2-1.0.4             | dynamictreesQuark-1.12.2-1.0.4.jar             | None                                     |
	| LCHIJA | rustic                                       | 1.1.6                    | rustic-1.1.6.jar                               | None                                     |
	| LCHIJA | thaumcraft                                   | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar               | None                                     |
	| LCHIJA | dynamictreestc                               | 1.12.2-1.4.2             | DynamicTreesTC-1.12.2-1.4.2.jar                | None                                     |
	| LCHIJA | dynamictreestconstruct                       | 1.12.2-1.2.2             | dynamictreesTConstruct-1.12.2-1.2.2.jar        | None                                     |
	| LCHIJA | dynamictreestheaether                        | 1.12.2-1.0.9             | dynamictreesTheAether-1.12.2-1.0.9.jar         | None                                     |
	| LCHIJA | exoticbirds                                  | 1.0                      | Exotic+Birds+1.12.2-3.2.0.jar                  | None                                     |
	| LCHIJA | grue                                         | 1.8.0                    | Grue-1.12.2-1.8.0.jar                          | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | llibrary                                     | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire                                   | 1.9.1                    | iceandfire-1.9.1-1.12.2.jar                    | None                                     |
	| LCHIJA | ichunutil                                    | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | refinedstorage                               | 1.6.16                   | refinedstorage-1.6.16.jar                      | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | railcraft                                    | 12.0.0                   | railcraft-12.0.0.jar                           | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | theoneprobe                                  | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                    | None                                     |
	| LCHIJA | thermalfoundation                            | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar | None                                     |
	| LCHIJA | immersiveengineering                         | 0.12-98                  | ImmersiveEngineering-0.12-98.jar               | None                                     |
	| LCHIJA | immersivecables                              | 1.3.2                    | ImmersiveCables-1.12.2-1.3.2.jar               | None                                     |
	| LCHIJA | inventorytweaks                              | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | jeresources                                  | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar        | None                                     |
	| LCHIJA | libraryex                                    | 1.1.3                    | LibraryEx-1.12.2-1.1.3.jar                     | None                                     |
	| LCHIJA | mobends                                      | 1.0.0-beta-20.06.20      | MoBends_1.12.2-1.0.0-beta-20.06.20.jar         | None                                     |
	| LCHIJA | netherex                                     | 2.1.8                    | NetherEx-1.12.2-2.1.8.jar                      | None                                     |
	| LCHIJA | portalgun                                    | 7.1.0                    | PortalGun-1.12.2-7.1.0.jar                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | resourceloader                               | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar              | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | storagedrawers                               | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar                | None                                     |
	| LCHIJA | storagedrawersextra                          | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar            | None                                     |
	| LCHIJA | beneath                                      | 1.7.0                    | The+Beneath-1.12.2-1.7.0.jar                   | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | thermalexpansion                             | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal.jar  | None                                     |
	| LCHIJA | thermaldynamics                              | 2.5.6                    | ThermalDynamics-1.12.2-2.5.6.1-universal.jar   | None                                     |
	| LCHIJA | tinkersaether                                | 1.4.0                    | tinkersaether-1.4.0.jar                        | None                                     |
	| LCHIJA | tinkersjei                                   | 1.2                      | tinkersjei-1.2.jar                             | None                                     |
	| LCHIJA | tumbleweed                                   | 1.12-0.4.7               | tumbleweed-1.12-0.4.7.jar                      | None                                     |
	| LCHIJA | mysttmtgravitymod                            | 2.9.1                    | UpAndDownAndAllAround-1.12.2-2.9.1.jar         | None                                     |
	| LCHIJA | dimstack                                     | 0.1.9                    | VerticallyStackedDimensions-1.12.2-0.1.9.jar   | None                                     |
	| LCHIJA | wanionlib                                    | 1.12.2-2.4               | WanionLib-1.12.2-2.4.jar                       | None                                     |
	| LCHIJA | wts                                          | 1.1.0                    | WTS-1.1.0.jar                                  | None                                     |
	| LCHIJA | reauth                                       | 3.6.0                    | reauth-3.6.0.jar                               | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| LCHIJA | hungeroverhaul                               | 1.12.2-1.3.3.jenkins148  | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar     | None                                     |
	| LCHIJA | mysticallib                                  | 1.12.2-1.9.0             | mysticallib-1.12.2-1.9.0.jar                   | None                                     |
	| LCHIJA | unidict                                      | 1.12.2-2.9.6             | UniDict-1.12.2-2.9.6.jar                       | None                                     |

	Loaded coremods (and transformers): 
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MovingWorldCore (movingworld-1.12-6.353-full.jar)
  
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
mysttmtgravitymod (UpAndDownAndAllAround-1.12.2-2.9.1.jar)
  uk.co.mysterymayhem.gravitymod.asm.Transformer
Vertically Stacked Dimensions ASM (VerticallyStackedDimensions-1.12.2-0.1.9.jar)
  cd4017be.dimstack.asm.ChunkPrimerTransformer
  cd4017be.dimstack.asm.BlockPortalTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-3.10.16' Renderer: 'AMD Radeon Pro 555 OpenGL Engine'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.2
	OpenGL: AMD Radeon Pro 555 OpenGL Engine GL version 2.1 ATI-3.10.16, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
```

Has anyone successfully used an APNG in CMM 2.0.9.1?

**Comment by forresthopkinsa** [comment]
Fixed in [my fork](https://github.com/forresthopkinsa/Custom-Main-Menu/releases/tag/v2.0.10)
