### ISSUE TITLE
Unable to load Image. Pink and Black box

### ISSUE THREAD

**Issue by WarpCircuit** [lumien231/Custom-Main-Menu#59]
This is the message given when I try to reload the main menu. The menu loads up fine, it's just that where the picture is suppose to be is the classic pink and block box of screwed up textures.

[18:52:56] [Client thread/WARN]: Failed to load texture: modpack:textures	itle.PNG
java.io.FileNotFoundException: modpack:textures	itle.PNG
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:71) ~[brg.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:29) ~[bpu.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(SourceFile:40) [bqf.class:?]
	at lumien.custommainmenu.lib.textures.TextureResourceLocation.bind(TextureResourceLocation.java:16) [TextureResourceLocation.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:390) [GuiCustom.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) [blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]

This is my JSON File

{
    "images":
    {
        "title":
        {
            "image" : "modpack:textures\title.PNG",
            "posX" : -137,
            "posY" : 30,
            "width" : 256,
            "height" : 128,
            "alignment" : "top_center"
        }
    },
    
    "buttons":
    {
        "singleplayer":
        {
            "text" : "menu.singleplayer",
            "posX" : -100,
            "posY" : 48,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },
        
        "multiplayer":
        {
            "text" : "menu.multiplayer",
            "posX" : -100,
            "posY" : 72,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
        
        "mods":
        {
            "text" : "Mods",
            "posX" : -100,
            "posY" : 96,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },
            
        "options":
        {
            "text" : "menu.options",
            "posX" : -100,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },
        
        "quit":
        {
            "text" : "menu.quit",
            "posX" : 2,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "quit"
            }
        },
        
        "language":
        {
            "text" : "",
            "posX" : -124,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
        
        "refresh":
        {
            "text" : "",
            "posX" : -154,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "texture" : "custommainmenu:textures/gui/buttons.png",
            "action" : 
            {
                "type" : "refresh"
            }
        }
    },
    
    "texts":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right"
        },
        
        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -50,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },
    
    "other":
    {
        "splash-text":
        {
            "posX" : 90,
            "posY" : 70,
            "color" : -256,
            "alignment" : "top_center",
            "file" : "texts/splashes.txt"
        },
        
        "panorama":
        {
            "images" : "minecraft:textures/gui/title/background/panorama_%c.png",
            "animate" : true,
            "animationSpeed" : 1,
            "blur" : true,
            "gradient" : true
        }
    }
}

I have resource loader and Custom main menu, both the latest version. I'm unsure of what's going on and I've resorted to asking you here. I have tried following the guides precisely and even following similar issues fix methods.  I have tried every variant of the text, including different slashes, capitols, and more folders. I am hoping someone can help me with this :(

![image](https://cloud.githubusercontent.com/assets/13289453/9422013/921b88be-4836-11e5-937c-e1e9f78fb287.png)

^^^^^^^^^^^^^^
The menu I get

**Comment by WarpCircuit** [comment]
Ok. I fixed it nevermind.

**Comment by kenijey** [comment]
how did you solved this?
