### ISSUE TITLE
Image Rendering as missing textures / Missing Texture Title

### ISSUE THREAD

**Issue by PixelBuddy** [lumien231/Custom-Main-Menu#98]
Hello, I've got some issues in image rendering, some of the pictures (especially edited in photoshop) render as missing texture. I've noticed that some of the downloaded images are working. I've got some Resource Loader installed. I've search for any help but none of them help me with this, please help.

Here is my mainmenu.json file
{
    "images":
    {
        "title":
        {
            "image" : "custommainmenu:textures/gui/title.png",
            "posX" : -137,
            "posY" : 30,
            "width" : 270,
            "height" : 85,
            "alignment" : "top_center"
        }
    },
    
    "buttons":
    {
        "singleplayer":
        {
            "text" : "menu.singleplayer",
			            "texture" : "modpack:texture/strip.png",
            "posX" : -100,
            "posY" : 48,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },
        
        "multiplayer":
        {
            "text" : "menu.multiplayer",
			            "texture" : "modpack:texture/strip.PNG",
            "posX" : -100,
            "posY" : 72,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
        
        "mods":
        {
            "text" : "Mods",
			            "texture" : "modpack:texture/strip.png",
            "posX" : -100,
            "posY" : 96,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },
            
        "options":
        {
            "text" : "menu.options",
			            "texture" : "modpack:texture/strip.png",
            "posX" : -100,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },
        
        "quit":
        {
            "text" : "menu.quit",
			            "texture" : "modpack:texture/strip.png",
            "posX" : 2,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "quit"
            }
        },
        
        "language":
        {
            "text" : "",
            "posX" : -124,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
        
        "refresh":
        {
            "text" : "",
            "posX" : -154,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "texture" : "custommainmenu:textures/gui/buttons.png",
            "action" : 
            {
                "type" : "refresh"
            }
        }
    },
    
    "texts":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right"
        },
        
        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -50,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },
    
    "other":
    {
        "splash-text":
        {
            "posX" : 90,
            "posY" : 70,
            "color" : -256,
            "alignment" : "top_center",
            "texts" : "file:minecraft:texts/splashes.txt"
        },
        
        "panorama":
        {
            "images" : "minecraft:textures/gui/title/background/panorama_%c.png",
            "animate" : true,
            "animationSpeed" : 1,
            "blur" : true,
            "gradient" : true
        }
    }
}

Here is the picture:
![capture14](https://cloud.githubusercontent.com/assets/17958499/13902934/05e0ba46-ee9d-11e5-906c-2eecc53cf677.PNG)

**Comment by lumien231** [comment]
Could i see your client log & folder structure please?

**Comment by PixelBuddy** [comment]
Thank you for responding. :)

Here is the folder structure:
![capture16](https://cloud.githubusercontent.com/assets/17958499/13988491/2dfe5914-f147-11e5-8663-a17621f76ac4.PNG)

Here is my log:
[22:39:59] [main/INFO]: Setting user: LilPixelBuddy
[22:40:02] [Client thread/INFO]: LWJGL Version: 2.9.1
[22:40:15] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Custom Main Menu, FMLFileResourcePack:Resource Loader
[22:40:16] [Sound Library Loader/INFO]: Sound engine started
[22:40:18] [Client thread/INFO]: Created: 16x16 textures/blocks-atlas
[22:40:18] [Client thread/INFO]: Created: 16x16 textures/items-atlas
[22:40:18] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Custom Main Menu, FMLFileResourcePack:Resource Loader, CustomResources, CustomOverridingResources
[22:40:19] [Client thread/INFO]: Created: 1024x512 textures/blocks-atlas
[22:40:19] [Client thread/INFO]: Created: 256x256 textures/items-atlas
[22:40:20] [Sound Library Loader/INFO]: Sound engine started
[22:40:20] [Client thread/WARN]: Failed to load texture: custommainmenu:textures/gui/title.png
java.io.FileNotFoundException: custommainmenu:textures/gui/title.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:67) ~[brg.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:29) ~[bpu.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:94) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:50) [bqf.class:?]
	at lumien.custommainmenu.lib.textures.TextureResourceLocation.bind(TextureResourceLocation.java:16) [TextureResourceLocation.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_73863_a(GuiCustom.java:368) [GuiCustom.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1397) [blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by TOLoneWolf** [comment]
Change "image" : "custommainmenu:textures/gui/title.png" to
"image" : "modpack:texture/title.png"
Will fix it if your trying to replace the minecraft title with your own custom one.

**Comment by lumien231** [comment]
Sorry, somehow forgot about this, what ^ said.
